/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { ApiContext } from "./../config/context"
import type { FieldValidationResolver, FieldAuthorizationResolver } from "./plugins"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    datetime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value is a JSON Web Token (JWT): https://jwt.io/introduction.
     */
    jwt<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JWT";
    /**
     * A field whose value is a valid decimal degrees latitude number (53.471): https://en.wikipedia.org/wiki/Latitude
     */
    latitude<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Latitude";
    /**
     * A field whose value is a valid decimal degrees longitude number (53.471): https://en.wikipedia.org/wiki/Longitude
     */
    longitude<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Longitude";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "URL";
    /**
     * A field whose value must be either: user, operator, admin
     */
    saveAs<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "SaveAsValue";
    /**
     * Floats that will have a value greater than 0.
     */
    positiveFloat<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "PositiveFloat";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    datetime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value is a JSON Web Token (JWT): https://jwt.io/introduction.
     */
    jwt<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JWT";
    /**
     * A field whose value is a valid decimal degrees latitude number (53.471): https://en.wikipedia.org/wiki/Latitude
     */
    latitude<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Latitude";
    /**
     * A field whose value is a valid decimal degrees longitude number (53.471): https://en.wikipedia.org/wiki/Longitude
     */
    longitude<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Longitude";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "URL";
    /**
     * A field whose value must be either: user, operator, admin
     */
    saveAs<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "SaveAsValue";
    /**
     * Floats that will have a value greater than 0.
     */
    positiveFloat<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "PositiveFloat";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CreateAccountInput: { // input type
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    firstName: string; // String!
    password: string; // String!
  }
  CreateBookingClaimInput: { // input type
    bookingId: string; // String!
    reason: string; // String!
    saveAs: NexusGenScalars['SaveAsValue']; // SaveAsValue!
  }
  CreateBookingMessageInput: { // input type
    bookingId: string; // String!
    content: string; // String!
    saveAs: string; // String!
  }
  CreateGenderOptionInput: { // input type
    nameEn: string; // String!
    nameFr: string; // String!
  }
  CreateHostingOptionInput: { // input type
    nameEn: string; // String!
    nameFr: string; // String!
  }
  CreateIndividualOperatorInput: { // input type
    acceptedSpecieOptionsIds: string[]; // [ID!]!
    birthDate: NexusGenScalars['Date']; // Date!
    description: string; // String!
    genderOptionId: string; // String!
    hostingOptionId: string; // String!
    languageOptionIds: string[]; // [ID!]!
    mainMediaId: string; // ID!
    ownAnimalsSpecieOptionsIds: string[]; // [ID!]!
    partnerId?: string | null; // String
    partnerPercentage?: number | null; // Int
    stripeAccountId?: string | null; // ID
  }
  CreateLanguageOptionInput: { // input type
    mediaId: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
  }
  CreateMediaInput: { // input type
    fileName: string; // String!
    fileType: string; // String!
    saveAs: string; // String!
  }
  CreateReviewInput: { // input type
    body?: string | null; // String
    bookingId: string; // String!
    saveAs: string; // String!
    score: NexusGenScalars['PositiveFloat']; // PositiveFloat!
    title: string; // String!
  }
  CreateServiceOptionInput: { // input type
    nameEn: string; // String!
    nameFr: string; // String!
  }
  CreateSpecieOptionInput: { // input type
    nameEn: string; // String!
    nameFr: string; // String!
  }
  CreateStaffAccountInput: { // input type
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    password: string; // String!
    phoneNumber: string; // String!
  }
  EmailAndPasswordInput: { // input type
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    password: string; // String!
  }
  ResetPasswordInput: { // input type
    newPassword: string; // String!
    token: NexusGenScalars['JWT']; // JWT!
  }
  SearchDonationsInput: { // input type
    donated?: boolean | null; // Boolean
    endDate?: NexusGenScalars['Date'] | null; // Date
    partnerId?: string | null; // String
    startDate?: NexusGenScalars['Date'] | null; // Date
  }
  SetBookingMessagesAsReadInput: { // input type
    ids: string[]; // [ID!]!
    readAt?: NexusGenScalars['Date'] | null; // Date
  }
  UpdateBookingMessageInput: { // input type
    content: string; // String!
    readAt?: NexusGenScalars['Date'] | null; // Date
  }
  UpdateGenderOptionInput: { // input type
    nameEn?: string | null; // String
    nameFr?: string | null; // String
  }
  UpdateHostingOptionInput: { // input type
    nameEn?: string | null; // String
    nameFr?: string | null; // String
  }
  UpdateIndividualOperatorInput: { // input type
    acceptedSpecieOptionsIds?: Array<string | null> | null; // [ID]
    birthDate?: NexusGenScalars['Date'] | null; // Date
    description?: string | null; // String
    genderOptionId?: string | null; // String
    hostingOptionId?: string | null; // String
    languageOptionIds?: Array<string | null> | null; // [ID]
    mainMediaId?: string | null; // ID
    ownAnimalsSpecieOptionsIds?: Array<string | null> | null; // [ID]
    partnerId?: string | null; // String
    partnerPercentage?: number | null; // Int
    stripeAccountId?: string | null; // ID
  }
  UpdateLanguageOptionInput: { // input type
    mediaId?: string | null; // ID
    nameEn?: string | null; // String
    nameFr?: string | null; // String
  }
  UpdateReviewInput: { // input type
    body?: string | null; // String
    score: NexusGenScalars['PositiveFloat']; // PositiveFloat!
    title: string; // String!
  }
  UpdateServiceOptionInput: { // input type
    nameEn?: string | null; // String
    nameFr?: string | null; // String
  }
  UpdateSpecieOptionInput: { // input type
    nameEn?: string | null; // String
    nameFr?: string | null; // String
  }
  VerifyUserInput: { // input type
    token: NexusGenScalars['JWT']; // JWT!
  }
}

export interface NexusGenEnums {
  BookingStatus: "BOTH_CONFIRMED" | "CANCELED" | "NONE_CONFIRMED" | "PAID" | "PAYMENT_AUTHORIZED" | "PENDING_OWNER_VALIDATION" | "PENDING_SITTER_VALIDATION" | "UNDER_REVIEW"
  ErrorCode: "BAD_REQUEST" | "FORBIDDEN" | "NOT_FOUND" | "UNABLE_TO_PROCESS" | "UNAUTHORIZED"
  ErrorMessage: "FORBIDDEN_YOU_DO_NOT_HAVE_ACCESS_TO_THIS_RESOURCE" | "RESOURCE_NOT_FOUND" | "UNABLE_TO_PROCESS_REQUEST_DUE_TO_CLIENT_ERROR" | "UNABLE_TO_PROCESS_REQUEST_DUE_TO_SERVER_ERROR" | "UNAUTHENTICATED_PLEASE_LOGIN"
  MediaType: "IMAGE" | "VIDEO"
  PaymentStatus: "AUTHORIZED_BUT_CANCELLED" | "AUTHORIZED_REQUIRE_CAPTURE" | "CAPTURED_AND_PAID" | "ERROR_SENDING_AUTH_REQUIRED_MAIL" | "ERROR_SENDING_INSUFFICIENT_FUNDS_MAIL" | "ERROR_SENDING_UNKOWN_ERROR_MAIL" | "FAILED_CAPTURE" | "FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED" | "FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED_MAIL_SENT" | "FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS" | "FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS_MAIL_SENT" | "FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR" | "FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR_MAIL_SENT" | "PENDING_AUTHORIZATION" | "SETUP_INTENT_CONFIRMED_REQUIRED_PAYMENT_INTENT_CREATION" | "SETUP_INTENT_PENDING_CONFIRMATION"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: Date
  DateTime: Date
  EmailAddress: string
  JSON: any
  JWT: string
  Latitude: number
  Longitude: number
  PositiveFloat: number
  SaveAsValue: 'user' | 'operator' | 'admin'
  URL: string
}

export interface NexusGenObjects {
  Account: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    verifiedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  AccountsList: { // root type
    accounts?: Array<NexusGenRootTypes['Account'] | null> | null; // [Account]
  }
  Booking: { // root type
    animalsIds?: Array<string | null> | null; // [ID]
    applictionFeeAmount?: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    canceled?: boolean | null; // Boolean
    canceledBy?: string | null; // String
    canceledReason?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    endDate?: NexusGenScalars['Date'] | null; // Date
    id: string; // String!
    operatorConfirmationDate?: NexusGenScalars['DateTime'] | null; // DateTime
    ownerConfirmationDate?: NexusGenScalars['DateTime'] | null; // DateTime
    paid?: boolean | null; // Boolean
    priceWithOutApplicationFee?: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    selectedOptions?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    startDate?: NexusGenScalars['Date'] | null; // Date
    underReview?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BookingMessagesList: { // root type
    bookingMessages?: Array<NexusGenRootTypes['BookingMessage'] | null> | null; // [BookingMessage]
  }
  BooleanResult: { // root type
    success?: boolean | null; // Boolean
  }
  ClaimsList: { // root type
    claims?: Array<NexusGenRootTypes['Claim'] | null> | null; // [Claim]
  }
  CronStatus: { // root type
    status?: string | null; // String
  }
  Donation: { // root type
    amountToDonate?: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationReceipt: { // root type
    amountDonated?: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationReceiptMedia: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    donationReceiptId?: string | null; // ID
    id: string; // String!
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationsList: { // root type
    donations?: Array<NexusGenRootTypes['Donation'] | null> | null; // [Donation]
  }
  GenderOption: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GenderOptionsList: { // root type
    genderOptions?: Array<NexusGenRootTypes['GenderOption'] | null> | null; // [GenderOption]
  }
  HostingOption: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  HostingOptionsList: { // root type
    hostingOptions?: Array<NexusGenRootTypes['HostingOption'] | null> | null; // [HostingOption]
  }
  IndividualOperator: { // root type
    acceptedSpecieOptionsIds?: Array<string | null> | null; // [String]
    accountId?: string | null; // ID
    birthDate?: NexusGenScalars['Date'] | null; // Date
    calendarUpdate?: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    genderOptionId?: string | null; // String
    hostingOptionId?: string | null; // String
    id: string; // String!
    languageOptionIds?: Array<string | null> | null; // [String]
    mainMediaId?: string | null; // String
    ownAnimalsSpecieOptionsIds?: Array<string | null> | null; // [String]
    partnerId?: string | null; // String
    partnerPercentage?: number | null; // Int
    stripeAccountId?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  InvalidArgument: { // root type
    key: string; // String!
    message: string; // String!
  }
  InvalidArgumentsError: { // root type
    invalidArguments: Array<NexusGenRootTypes['InvalidArgument'] | null>; // [InvalidArgument]!
  }
  IsActiveOperatorMainMediaError: { // root type
    activeOperatorMainMediaError: string; // String!
  }
  IsActiveOperatorWithNoReplacementMediaError: { // root type
    activeOperatorWithNoReplacementMediaError: string; // String!
  }
  LanguageOption: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  LanguageOptionMedia: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    languageOptionId?: string | null; // ID
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  LanguageOptionsList: { // root type
    languageOptions?: Array<NexusGenRootTypes['LanguageOption'] | null> | null; // [LanguageOption]
  }
  MediasList: { // root type
    medias?: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
  }
  MessageMedia: { // root type
    bookingMessageId?: string | null; // ID
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Mutation: {};
  NotFoundError: {};
  OperatorBookingMessage: { // root type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    operatorId?: string | null; // ID
    readAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorClaim: { // root type
    bookingId: string; // ID!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    operatorId?: string | null; // ID
    reason: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorMedia: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    operatorId?: string | null; // ID
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorReview: { // root type
    body?: string | null; // String
    bookingId?: string | null; // ID
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    operatorId?: string | null; // ID
    score: number; // Float!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: {};
  ReviewsList: { // root type
    reviews?: Array<NexusGenRootTypes['Review'] | null> | null; // [Review]
  }
  ServiceOption: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ServiceOptionsList: { // root type
    serviceOptions?: Array<NexusGenRootTypes['ServiceOption'] | null> | null; // [ServiceOption]
  }
  SharedMedia: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    operatorId?: string | null; // ID
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId?: string | null; // ID
  }
  SpecieOption: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  SpecieOptionsList: { // root type
    specieOptions?: Array<NexusGenRootTypes['SpecieOption'] | null> | null; // [SpecieOption]
  }
  Staff: { // root type
    access?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    id: string; // String!
    phoneNumber?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StaffsList: { // root type
    staffs?: Array<NexusGenRootTypes['Staff'] | null> | null; // [Staff]
  }
  StorageInfos: { // root type
    signedRequest?: string | null; // String
    url?: string | null; // String
  }
  StripePayment: { // root type
    bookingId?: string | null; // ID
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    errorCode?: string | null; // String
    id: string; // String!
    status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Subscription: {};
  UnableToProcessError: {};
  User: { // root type
    accountId?: string | null; // ID
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    firstName: string; // String!
    id: string; // String!
    lastName?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserAuthenticationError: {};
  UserBookingMessage: { // root type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    readAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId?: string | null; // ID
  }
  UserClaim: { // root type
    bookingId: string; // ID!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    reason: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId?: string | null; // ID
  }
  UserForbiddenError: {};
  UserMedia: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType?: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId?: string | null; // ID
  }
  UserReview: { // root type
    body?: string | null; // String
    bookingId?: string | null; // ID
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    score: number; // Float!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId?: string | null; // ID
  }
  UsersList: { // root type
    users?: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
}

export interface NexusGenInterfaces {
  Actor: NexusGenRootTypes['IndividualOperator'] | NexusGenRootTypes['User'];
  BookingMessage: NexusGenRootTypes['OperatorBookingMessage'] | NexusGenRootTypes['UserBookingMessage'];
  Claim: NexusGenRootTypes['OperatorClaim'] | NexusGenRootTypes['UserClaim'];
  Media: NexusGenRootTypes['DonationReceiptMedia'] | NexusGenRootTypes['LanguageOptionMedia'] | NexusGenRootTypes['MessageMedia'] | NexusGenRootTypes['OperatorMedia'] | NexusGenRootTypes['SharedMedia'] | NexusGenRootTypes['UserMedia'];
  Node: NexusGenRootTypes['Account'] | NexusGenRootTypes['Booking'] | NexusGenRootTypes['Donation'] | NexusGenRootTypes['DonationReceipt'] | NexusGenRootTypes['DonationReceiptMedia'] | NexusGenRootTypes['GenderOption'] | NexusGenRootTypes['HostingOption'] | NexusGenRootTypes['IndividualOperator'] | NexusGenRootTypes['LanguageOption'] | NexusGenRootTypes['LanguageOptionMedia'] | NexusGenRootTypes['MessageMedia'] | NexusGenRootTypes['OperatorBookingMessage'] | NexusGenRootTypes['OperatorClaim'] | NexusGenRootTypes['OperatorMedia'] | NexusGenRootTypes['OperatorReview'] | NexusGenRootTypes['ServiceOption'] | NexusGenRootTypes['SharedMedia'] | NexusGenRootTypes['SpecieOption'] | NexusGenRootTypes['Staff'] | NexusGenRootTypes['StripePayment'] | NexusGenRootTypes['User'] | NexusGenRootTypes['UserBookingMessage'] | NexusGenRootTypes['UserClaim'] | NexusGenRootTypes['UserMedia'] | NexusGenRootTypes['UserReview'];
  Operator: NexusGenRootTypes['IndividualOperator'];
  Payment: NexusGenRootTypes['StripePayment'];
  Review: NexusGenRootTypes['OperatorReview'] | NexusGenRootTypes['UserReview'];
}

export interface NexusGenUnions {
  AccountByIdResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  AccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  AllAccountsResult: NexusGenRootTypes['AccountsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  AllStaffsResult: NexusGenRootTypes['StaffsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  AllUsersResult: NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'] | NexusGenRootTypes['UsersList'];
  BookingMessageByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorBookingMessage'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserBookingMessage'] | NexusGenRootTypes['UserForbiddenError'];
  BookingMessagesResult: NexusGenRootTypes['BookingMessagesList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  BookingPayment: NexusGenRootTypes['StripePayment'];
  ClaimByIdResult: NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorClaim'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserClaim'] | NexusGenRootTypes['UserForbiddenError'];
  ClaimsResult: NexusGenRootTypes['ClaimsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateAccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  CreateBookingClaimResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['OperatorClaim'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserClaim'];
  CreateBookingMessageResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['OperatorBookingMessage'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserBookingMessage'];
  CreateGenderOptionResult: NexusGenRootTypes['GenderOption'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateHostingOptionResult: NexusGenRootTypes['HostingOption'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateIndividualOperatorResult: NexusGenRootTypes['IndividualOperator'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  CreateLanguageOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['LanguageOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateMediaResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['StorageInfos'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  CreateReviewResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['OperatorReview'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserReview'];
  CreateServiceOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['ServiceOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateSpecieOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['SpecieOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CreateStaffAccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  CronSubscriptionsResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CurrentAccountResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CurrentOperatorDonationsResult: NexusGenRootTypes['DonationsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CurrentOperatorMediaResult: NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorMedia'] | NexusGenRootTypes['SharedMedia'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  CurrentUserMediaResult: NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['SharedMedia'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'] | NexusGenRootTypes['UserMedia'];
  DeleteAccountResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'];
  DeleteBookingMessageResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  DeleteClaimResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  DeleteGenderOptionResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  DeleteHostingOptionResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  DeleteLanguageOptionResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  DeleteMediaResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['IsActiveOperatorMainMediaError'] | NexusGenRootTypes['IsActiveOperatorWithNoReplacementMediaError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  DeleteReviewResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  DeleteServiceOptionResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  DeleteSpecieOptionResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  DonationByIdResult: NexusGenRootTypes['Donation'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'];
  DonationsResult: NexusGenRootTypes['DonationsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  GenderOptionByIdResult: NexusGenRootTypes['GenderOption'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  GenderOptionsResult: NexusGenRootTypes['GenderOptionsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  GetCronStatusResult: NexusGenRootTypes['CronStatus'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  HostingOptionByIdResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  HostingOptionsResult: NexusGenRootTypes['HostingOptionsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  IndividualOperatorResult: NexusGenRootTypes['IndividualOperator'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  LanguageOptionByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['LanguageOption'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  LanguageOptionsResult: NexusGenRootTypes['LanguageOptionsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  LostPasswordResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['NotFoundError'];
  MediaByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorMedia'] | NexusGenRootTypes['SharedMedia'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'] | NexusGenRootTypes['UserMedia'];
  MediasResult: NexusGenRootTypes['MediasList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  ModifyEmailResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  ModifyPasswordResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UserAuthenticationError'];
  ResetPasswordResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  ReviewByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorReview'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'] | NexusGenRootTypes['UserReview'];
  ReviewsResult: NexusGenRootTypes['ReviewsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  SearchDonationsResult: NexusGenRootTypes['DonationsList'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'];
  SendVerificationEmailResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
  ServiceOptionByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['ServiceOption'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  ServiceOptionsResult: NexusGenRootTypes['ServiceOptionsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  SetBookingMessagesAsReadResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'];
  SignInResult: NexusGenRootTypes['Account'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
  SignOutResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['UserAuthenticationError'];
  SpecieOptionByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['SpecieOption'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  SpecieOptionsResult: NexusGenRootTypes['SpecieOptionsList'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  StaffByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['Staff'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  StartCronResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  StopCronResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UpdateBookingMessageResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorBookingMessage'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserBookingMessage'];
  UpdateGenderOptionResult: NexusGenRootTypes['GenderOption'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UpdateHostingOptionResult: NexusGenRootTypes['HostingOption'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UpdateIndividualOperatorResult: NexusGenRootTypes['IndividualOperator'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
  UpdateLanguageOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['LanguageOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UpdateReviewResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['OperatorReview'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserReview'];
  UpdateServiceOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['ServiceOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UpdateSpecieOptionResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['SpecieOption'] | NexusGenRootTypes['UnableToProcessError'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  UserByIdResult: NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['User'] | NexusGenRootTypes['UserAuthenticationError'] | NexusGenRootTypes['UserForbiddenError'];
  VerifyUserResult: NexusGenRootTypes['BooleanResult'] | NexusGenRootTypes['InvalidArgumentsError'] | NexusGenRootTypes['NotFoundError'] | NexusGenRootTypes['UnableToProcessError'];
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Account: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    id: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    verifiedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  AccountsList: { // field return type
    accounts: Array<NexusGenRootTypes['Account'] | null> | null; // [Account]
  }
  Booking: { // field return type
    animalsIds: Array<string | null> | null; // [ID]
    applictionFeeAmount: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    canceled: boolean | null; // Boolean
    canceledBy: string | null; // String
    canceledReason: string | null; // String
    claims: Array<NexusGenRootTypes['Claim'] | null> | null; // [Claim]
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    endDate: NexusGenScalars['Date'] | null; // Date
    id: string; // String!
    messages: Array<NexusGenRootTypes['BookingMessage'] | null> | null; // [BookingMessage]
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorConfirmationDate: NexusGenScalars['DateTime'] | null; // DateTime
    ownerConfirmationDate: NexusGenScalars['DateTime'] | null; // DateTime
    paid: boolean | null; // Boolean
    payment: NexusGenRootTypes['BookingPayment'] | null; // BookingPayment
    priceWithOutApplicationFee: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    reviews: Array<NexusGenRootTypes['Review'] | null> | null; // [Review]
    selectedOptions: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    service: NexusGenRootTypes['ServiceOption'] | null; // ServiceOption
    startDate: NexusGenScalars['Date'] | null; // Date
    status: NexusGenEnums['BookingStatus'] | null; // BookingStatus
    underReview: boolean | null; // Boolean
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
  }
  BookingMessagesList: { // field return type
    bookingMessages: Array<NexusGenRootTypes['BookingMessage'] | null> | null; // [BookingMessage]
  }
  BooleanResult: { // field return type
    success: boolean | null; // Boolean
  }
  ClaimsList: { // field return type
    claims: Array<NexusGenRootTypes['Claim'] | null> | null; // [Claim]
  }
  CronStatus: { // field return type
    status: string | null; // String
  }
  Donation: { // field return type
    amountToDonate: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationReceipt: { // field return type
    amountDonated: NexusGenScalars['PositiveFloat'] | null; // PositiveFloat
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationReceiptMedia: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    donationReceipt: NexusGenRootTypes['DonationReceipt'] | null; // DonationReceipt
    donationReceiptId: string | null; // ID
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DonationsList: { // field return type
    donations: Array<NexusGenRootTypes['Donation'] | null> | null; // [Donation]
  }
  GenderOption: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GenderOptionsList: { // field return type
    genderOptions: Array<NexusGenRootTypes['GenderOption'] | null> | null; // [GenderOption]
  }
  HostingOption: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  HostingOptionsList: { // field return type
    hostingOptions: Array<NexusGenRootTypes['HostingOption'] | null> | null; // [HostingOption]
  }
  IndividualOperator: { // field return type
    acceptedSpecieOptionsIds: Array<string | null> | null; // [String]
    account: NexusGenRootTypes['Account'] | null; // Account
    accountId: string | null; // ID
    birthDate: NexusGenScalars['Date'] | null; // Date
    calendarUpdate: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    genderOptionId: string | null; // String
    hostingOptionId: string | null; // String
    id: string; // String!
    languageOptionIds: Array<string | null> | null; // [String]
    mainMediaId: string | null; // String
    medias: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
    ownAnimalsSpecieOptionsIds: Array<string | null> | null; // [String]
    partnerId: string | null; // String
    partnerPercentage: number | null; // Int
    stripeAccountId: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  InvalidArgument: { // field return type
    key: string; // String!
    message: string; // String!
  }
  InvalidArgumentsError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    invalidArguments: Array<NexusGenRootTypes['InvalidArgument'] | null>; // [InvalidArgument]!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  IsActiveOperatorMainMediaError: { // field return type
    activeOperatorMainMediaError: string; // String!
  }
  IsActiveOperatorWithNoReplacementMediaError: { // field return type
    activeOperatorWithNoReplacementMediaError: string; // String!
  }
  LanguageOption: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    media: NexusGenRootTypes['Media'] | null; // Media
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  LanguageOptionMedia: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    language: NexusGenRootTypes['LanguageOption'] | null; // LanguageOption
    languageOptionId: string | null; // ID
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  LanguageOptionsList: { // field return type
    languageOptions: Array<NexusGenRootTypes['LanguageOption'] | null> | null; // [LanguageOption]
  }
  MediasList: { // field return type
    medias: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
  }
  MessageMedia: { // field return type
    bookingMessageId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    message: NexusGenRootTypes['BookingMessage'] | null; // BookingMessage
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Mutation: { // field return type
    createAccount: NexusGenRootTypes['CreateAccountResult'] | null; // CreateAccountResult
    createBookingClaim: NexusGenRootTypes['CreateBookingClaimResult'] | null; // CreateBookingClaimResult
    createBookingMessage: NexusGenRootTypes['CreateBookingMessageResult'] | null; // CreateBookingMessageResult
    createGenderOption: NexusGenRootTypes['CreateGenderOptionResult'] | null; // CreateGenderOptionResult
    createHostingOption: NexusGenRootTypes['CreateHostingOptionResult'] | null; // CreateHostingOptionResult
    createIndividualOperator: NexusGenRootTypes['CreateIndividualOperatorResult'] | null; // CreateIndividualOperatorResult
    createLanguageOption: NexusGenRootTypes['CreateLanguageOptionResult'] | null; // CreateLanguageOptionResult
    createMedia: NexusGenRootTypes['CreateMediaResult'] | null; // CreateMediaResult
    createReview: NexusGenRootTypes['CreateReviewResult'] | null; // CreateReviewResult
    createServiceOption: NexusGenRootTypes['CreateServiceOptionResult'] | null; // CreateServiceOptionResult
    createSpecieOption: NexusGenRootTypes['CreateSpecieOptionResult'] | null; // CreateSpecieOptionResult
    createStaffAccount: NexusGenRootTypes['CreateStaffAccountResult'] | null; // CreateStaffAccountResult
    deleteAccount: NexusGenRootTypes['DeleteAccountResult'] | null; // DeleteAccountResult
    deleteBookingMessage: NexusGenRootTypes['DeleteBookingMessageResult'] | null; // DeleteBookingMessageResult
    deleteClaim: NexusGenRootTypes['DeleteClaimResult'] | null; // DeleteClaimResult
    deleteGenderOption: NexusGenRootTypes['DeleteGenderOptionResult'] | null; // DeleteGenderOptionResult
    deleteHostingOption: NexusGenRootTypes['DeleteHostingOptionResult'] | null; // DeleteHostingOptionResult
    deleteLanguageOption: NexusGenRootTypes['DeleteLanguageOptionResult'] | null; // DeleteLanguageOptionResult
    deleteMedia: NexusGenRootTypes['DeleteMediaResult'] | null; // DeleteMediaResult
    deleteReview: NexusGenRootTypes['DeleteReviewResult'] | null; // DeleteReviewResult
    deleteServiceOption: NexusGenRootTypes['DeleteServiceOptionResult'] | null; // DeleteServiceOptionResult
    deleteSpecieOption: NexusGenRootTypes['DeleteSpecieOptionResult'] | null; // DeleteSpecieOptionResult
    lostPassword: NexusGenRootTypes['LostPasswordResult'] | null; // LostPasswordResult
    modifyEmail: NexusGenRootTypes['ModifyEmailResult'] | null; // ModifyEmailResult
    modifyPassword: NexusGenRootTypes['ModifyPasswordResult'] | null; // ModifyPasswordResult
    resetPassword: NexusGenRootTypes['ResetPasswordResult'] | null; // ResetPasswordResult
    sendVerificationEmail: NexusGenRootTypes['SendVerificationEmailResult'] | null; // SendVerificationEmailResult
    setAsRead: NexusGenRootTypes['SetBookingMessagesAsReadResult'] | null; // SetBookingMessagesAsReadResult
    signIn: NexusGenRootTypes['SignInResult'] | null; // SignInResult
    signOut: NexusGenRootTypes['SignOutResult'] | null; // SignOutResult
    startCron: NexusGenRootTypes['StartCronResult'] | null; // StartCronResult
    stopCron: NexusGenRootTypes['StopCronResult'] | null; // StopCronResult
    updateBookingMessage: NexusGenRootTypes['UpdateBookingMessageResult'] | null; // UpdateBookingMessageResult
    updateGenderOption: NexusGenRootTypes['UpdateGenderOptionResult'] | null; // UpdateGenderOptionResult
    updateHostingOption: NexusGenRootTypes['UpdateHostingOptionResult'] | null; // UpdateHostingOptionResult
    updateIndividualOperator: NexusGenRootTypes['IndividualOperatorResult'] | null; // IndividualOperatorResult
    updateLanguageOption: NexusGenRootTypes['UpdateLanguageOptionResult'] | null; // UpdateLanguageOptionResult
    updateReview: NexusGenRootTypes['UpdateReviewResult'] | null; // UpdateReviewResult
    updateServiceOption: NexusGenRootTypes['UpdateServiceOptionResult'] | null; // UpdateServiceOptionResult
    updateSpecieOption: NexusGenRootTypes['UpdateSpecieOptionResult'] | null; // UpdateSpecieOptionResult
    verifyUser: NexusGenRootTypes['VerifyUserResult'] | null; // VerifyUserResult
  }
  NotFoundError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  OperatorBookingMessage: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    medias: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorId: string | null; // ID
    readAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorClaim: { // field return type
    bookingId: string; // ID!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorId: string | null; // ID
    reason: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorMedia: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorId: string | null; // ID
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  OperatorReview: { // field return type
    body: string | null; // String
    booking: NexusGenRootTypes['Booking'] | null; // Booking
    bookingId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorId: string | null; // ID
    score: number; // Float!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: { // field return type
    accountById: NexusGenRootTypes['AccountByIdResult'] | null; // AccountByIdResult
    allAccounts: NexusGenRootTypes['AllAccountsResult'] | null; // AllAccountsResult
    allStaffs: NexusGenRootTypes['AllStaffsResult'] | null; // AllStaffsResult
    allUsers: NexusGenRootTypes['AllUsersResult'] | null; // AllUsersResult
    bookingMessageById: NexusGenRootTypes['BookingMessageByIdResult'] | null; // BookingMessageByIdResult
    bookingMessages: NexusGenRootTypes['BookingMessagesResult'] | null; // BookingMessagesResult
    claimById: NexusGenRootTypes['ClaimByIdResult'] | null; // ClaimByIdResult
    claims: NexusGenRootTypes['ClaimsResult'] | null; // ClaimsResult
    currentAccount: NexusGenRootTypes['CurrentAccountResult'] | null; // CurrentAccountResult
    currentOperatorDonations: NexusGenRootTypes['CurrentOperatorDonationsResult'] | null; // CurrentOperatorDonationsResult
    currentOperatorMedia: NexusGenRootTypes['CurrentOperatorMediaResult'] | null; // CurrentOperatorMediaResult
    currentUserMedia: NexusGenRootTypes['CurrentUserMediaResult'] | null; // CurrentUserMediaResult
    donationById: NexusGenRootTypes['DonationByIdResult'] | null; // DonationByIdResult
    donations: NexusGenRootTypes['DonationsResult'] | null; // DonationsResult
    genderOptionById: NexusGenRootTypes['GenderOptionByIdResult'] | null; // GenderOptionByIdResult
    gendersOptions: NexusGenRootTypes['GenderOptionsResult'] | null; // GenderOptionsResult
    getCronStatus: NexusGenRootTypes['GetCronStatusResult'] | null; // GetCronStatusResult
    hostingOptionById: NexusGenRootTypes['HostingOptionByIdResult'] | null; // HostingOptionByIdResult
    hostingsOptions: NexusGenRootTypes['HostingOptionsResult'] | null; // HostingOptionsResult
    languageOptionById: NexusGenRootTypes['LanguageOptionByIdResult'] | null; // LanguageOptionByIdResult
    languagesOptions: NexusGenRootTypes['LanguageOptionsResult'] | null; // LanguageOptionsResult
    mediaById: NexusGenRootTypes['MediaByIdResult'] | null; // MediaByIdResult
    medias: NexusGenRootTypes['MediasResult'] | null; // MediasResult
    reviewById: NexusGenRootTypes['ReviewByIdResult'] | null; // ReviewByIdResult
    reviews: NexusGenRootTypes['ReviewsResult'] | null; // ReviewsResult
    searchDonations: NexusGenRootTypes['SearchDonationsResult'] | null; // SearchDonationsResult
    serviceOptionById: NexusGenRootTypes['ServiceOptionByIdResult'] | null; // ServiceOptionByIdResult
    servicesOptions: NexusGenRootTypes['ServiceOptionsResult'] | null; // ServiceOptionsResult
    specieOptionById: NexusGenRootTypes['SpecieOptionByIdResult'] | null; // SpecieOptionByIdResult
    speciesOptions: NexusGenRootTypes['SpecieOptionsResult'] | null; // SpecieOptionsResult
    staffById: NexusGenRootTypes['StaffByIdResult'] | null; // StaffByIdResult
    userById: NexusGenRootTypes['UserByIdResult'] | null; // UserByIdResult
  }
  ReviewsList: { // field return type
    reviews: Array<NexusGenRootTypes['Review'] | null> | null; // [Review]
  }
  ServiceOption: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ServiceOptionsList: { // field return type
    serviceOptions: Array<NexusGenRootTypes['ServiceOption'] | null> | null; // [ServiceOption]
  }
  SharedMedia: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    operator: NexusGenRootTypes['Operator'] | null; // Operator
    operatorId: string | null; // ID
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // ID
  }
  SpecieOption: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    nameEn: string; // String!
    nameFr: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  SpecieOptionsList: { // field return type
    specieOptions: Array<NexusGenRootTypes['SpecieOption'] | null> | null; // [SpecieOption]
  }
  Staff: { // field return type
    access: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    id: string; // String!
    phoneNumber: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StaffsList: { // field return type
    staffs: Array<NexusGenRootTypes['Staff'] | null> | null; // [Staff]
  }
  StorageInfos: { // field return type
    signedRequest: string | null; // String
    url: string | null; // String
  }
  StripePayment: { // field return type
    booking: NexusGenRootTypes['Booking'] | null; // Booking
    bookingId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    errorCode: string | null; // String
    id: string; // String!
    status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Subscription: { // field return type
    errorsEmailCronSub: NexusGenRootTypes['CronSubscriptionsResult'] | null; // CronSubscriptionsResult
    pendingPaymentCronSub: NexusGenRootTypes['CronSubscriptionsResult'] | null; // CronSubscriptionsResult
    setupIntentCronSub: NexusGenRootTypes['CronSubscriptionsResult'] | null; // CronSubscriptionsResult
  }
  UnableToProcessError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  User: { // field return type
    accountId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    firstName: string; // String!
    id: string; // String!
    lastName: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserAuthenticationError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  UserBookingMessage: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    medias: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
    readAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // ID
  }
  UserClaim: { // field return type
    bookingId: string; // ID!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    reason: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // ID
  }
  UserForbiddenError: { // field return type
    code: NexusGenEnums['ErrorCode']; // ErrorCode!
    message: NexusGenEnums['ErrorMessage']; // ErrorMessage!
  }
  UserMedia: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // ID
  }
  UserReview: { // field return type
    body: string | null; // String
    booking: NexusGenRootTypes['Booking'] | null; // Booking
    bookingId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    score: number; // Float!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
    userId: string | null; // ID
  }
  UsersList: { // field return type
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  Actor: { // field return type
    accountId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  BookingMessage: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    medias: Array<NexusGenRootTypes['Media'] | null> | null; // [Media]
    readAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Claim: { // field return type
    bookingId: string; // ID!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    reason: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Media: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    mediaType: NexusGenEnums['MediaType'] | null; // MediaType
    storeUrl: NexusGenScalars['URL']; // URL!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Node: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Operator: { // field return type
    acceptedSpecieOptionsIds: Array<string | null> | null; // [String]
    accountId: string | null; // ID
    calendarUpdate: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    hostingOptionId: string | null; // String
    id: string; // String!
    languageOptionIds: Array<string | null> | null; // [String]
    mainMediaId: string | null; // String
    ownAnimalsSpecieOptionsIds: Array<string | null> | null; // [String]
    partnerId: string | null; // String
    partnerPercentage: number | null; // Int
    stripeAccountId: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Payment: { // field return type
    bookingId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Review: { // field return type
    body: string | null; // String
    booking: NexusGenRootTypes['Booking'] | null; // Booking
    bookingId: string | null; // ID
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    score: number; // Float!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    createdAt: 'DateTime'
    email: 'EmailAddress'
    id: 'String'
    updatedAt: 'DateTime'
    user: 'User'
    verifiedAt: 'DateTime'
  }
  AccountsList: { // field return type name
    accounts: 'Account'
  }
  Booking: { // field return type name
    animalsIds: 'ID'
    applictionFeeAmount: 'PositiveFloat'
    canceled: 'Boolean'
    canceledBy: 'String'
    canceledReason: 'String'
    claims: 'Claim'
    createdAt: 'DateTime'
    endDate: 'Date'
    id: 'String'
    messages: 'BookingMessage'
    operator: 'Operator'
    operatorConfirmationDate: 'DateTime'
    ownerConfirmationDate: 'DateTime'
    paid: 'Boolean'
    payment: 'BookingPayment'
    priceWithOutApplicationFee: 'PositiveFloat'
    reviews: 'Review'
    selectedOptions: 'JSON'
    service: 'ServiceOption'
    startDate: 'Date'
    status: 'BookingStatus'
    underReview: 'Boolean'
    updatedAt: 'DateTime'
    user: 'User'
  }
  BookingMessagesList: { // field return type name
    bookingMessages: 'BookingMessage'
  }
  BooleanResult: { // field return type name
    success: 'Boolean'
  }
  ClaimsList: { // field return type name
    claims: 'Claim'
  }
  CronStatus: { // field return type name
    status: 'String'
  }
  Donation: { // field return type name
    amountToDonate: 'PositiveFloat'
    createdAt: 'DateTime'
    id: 'String'
    updatedAt: 'DateTime'
  }
  DonationReceipt: { // field return type name
    amountDonated: 'PositiveFloat'
    createdAt: 'DateTime'
    id: 'String'
    updatedAt: 'DateTime'
  }
  DonationReceiptMedia: { // field return type name
    createdAt: 'DateTime'
    donationReceipt: 'DonationReceipt'
    donationReceiptId: 'ID'
    id: 'String'
    mediaType: 'MediaType'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
  }
  DonationsList: { // field return type name
    donations: 'Donation'
  }
  GenderOption: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    nameEn: 'String'
    nameFr: 'String'
    updatedAt: 'DateTime'
  }
  GenderOptionsList: { // field return type name
    genderOptions: 'GenderOption'
  }
  HostingOption: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    nameEn: 'String'
    nameFr: 'String'
    updatedAt: 'DateTime'
  }
  HostingOptionsList: { // field return type name
    hostingOptions: 'HostingOption'
  }
  IndividualOperator: { // field return type name
    acceptedSpecieOptionsIds: 'String'
    account: 'Account'
    accountId: 'ID'
    birthDate: 'Date'
    calendarUpdate: 'DateTime'
    createdAt: 'DateTime'
    description: 'String'
    genderOptionId: 'String'
    hostingOptionId: 'String'
    id: 'String'
    languageOptionIds: 'String'
    mainMediaId: 'String'
    medias: 'Media'
    ownAnimalsSpecieOptionsIds: 'String'
    partnerId: 'String'
    partnerPercentage: 'Int'
    stripeAccountId: 'String'
    updatedAt: 'DateTime'
  }
  InvalidArgument: { // field return type name
    key: 'String'
    message: 'String'
  }
  InvalidArgumentsError: { // field return type name
    code: 'ErrorCode'
    invalidArguments: 'InvalidArgument'
    message: 'ErrorMessage'
  }
  IsActiveOperatorMainMediaError: { // field return type name
    activeOperatorMainMediaError: 'String'
  }
  IsActiveOperatorWithNoReplacementMediaError: { // field return type name
    activeOperatorWithNoReplacementMediaError: 'String'
  }
  LanguageOption: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    media: 'Media'
    nameEn: 'String'
    nameFr: 'String'
    updatedAt: 'DateTime'
  }
  LanguageOptionMedia: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    language: 'LanguageOption'
    languageOptionId: 'ID'
    mediaType: 'MediaType'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
  }
  LanguageOptionsList: { // field return type name
    languageOptions: 'LanguageOption'
  }
  MediasList: { // field return type name
    medias: 'Media'
  }
  MessageMedia: { // field return type name
    bookingMessageId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    mediaType: 'MediaType'
    message: 'BookingMessage'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
  }
  Mutation: { // field return type name
    createAccount: 'CreateAccountResult'
    createBookingClaim: 'CreateBookingClaimResult'
    createBookingMessage: 'CreateBookingMessageResult'
    createGenderOption: 'CreateGenderOptionResult'
    createHostingOption: 'CreateHostingOptionResult'
    createIndividualOperator: 'CreateIndividualOperatorResult'
    createLanguageOption: 'CreateLanguageOptionResult'
    createMedia: 'CreateMediaResult'
    createReview: 'CreateReviewResult'
    createServiceOption: 'CreateServiceOptionResult'
    createSpecieOption: 'CreateSpecieOptionResult'
    createStaffAccount: 'CreateStaffAccountResult'
    deleteAccount: 'DeleteAccountResult'
    deleteBookingMessage: 'DeleteBookingMessageResult'
    deleteClaim: 'DeleteClaimResult'
    deleteGenderOption: 'DeleteGenderOptionResult'
    deleteHostingOption: 'DeleteHostingOptionResult'
    deleteLanguageOption: 'DeleteLanguageOptionResult'
    deleteMedia: 'DeleteMediaResult'
    deleteReview: 'DeleteReviewResult'
    deleteServiceOption: 'DeleteServiceOptionResult'
    deleteSpecieOption: 'DeleteSpecieOptionResult'
    lostPassword: 'LostPasswordResult'
    modifyEmail: 'ModifyEmailResult'
    modifyPassword: 'ModifyPasswordResult'
    resetPassword: 'ResetPasswordResult'
    sendVerificationEmail: 'SendVerificationEmailResult'
    setAsRead: 'SetBookingMessagesAsReadResult'
    signIn: 'SignInResult'
    signOut: 'SignOutResult'
    startCron: 'StartCronResult'
    stopCron: 'StopCronResult'
    updateBookingMessage: 'UpdateBookingMessageResult'
    updateGenderOption: 'UpdateGenderOptionResult'
    updateHostingOption: 'UpdateHostingOptionResult'
    updateIndividualOperator: 'IndividualOperatorResult'
    updateLanguageOption: 'UpdateLanguageOptionResult'
    updateReview: 'UpdateReviewResult'
    updateServiceOption: 'UpdateServiceOptionResult'
    updateSpecieOption: 'UpdateSpecieOptionResult'
    verifyUser: 'VerifyUserResult'
  }
  NotFoundError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  OperatorBookingMessage: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    medias: 'Media'
    operator: 'Operator'
    operatorId: 'ID'
    readAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  OperatorClaim: { // field return type name
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    operator: 'Operator'
    operatorId: 'ID'
    reason: 'String'
    updatedAt: 'DateTime'
  }
  OperatorMedia: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    mediaType: 'MediaType'
    operator: 'Operator'
    operatorId: 'ID'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
  }
  OperatorReview: { // field return type name
    body: 'String'
    booking: 'Booking'
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    operator: 'Operator'
    operatorId: 'ID'
    score: 'Float'
    title: 'String'
    updatedAt: 'DateTime'
  }
  Query: { // field return type name
    accountById: 'AccountByIdResult'
    allAccounts: 'AllAccountsResult'
    allStaffs: 'AllStaffsResult'
    allUsers: 'AllUsersResult'
    bookingMessageById: 'BookingMessageByIdResult'
    bookingMessages: 'BookingMessagesResult'
    claimById: 'ClaimByIdResult'
    claims: 'ClaimsResult'
    currentAccount: 'CurrentAccountResult'
    currentOperatorDonations: 'CurrentOperatorDonationsResult'
    currentOperatorMedia: 'CurrentOperatorMediaResult'
    currentUserMedia: 'CurrentUserMediaResult'
    donationById: 'DonationByIdResult'
    donations: 'DonationsResult'
    genderOptionById: 'GenderOptionByIdResult'
    gendersOptions: 'GenderOptionsResult'
    getCronStatus: 'GetCronStatusResult'
    hostingOptionById: 'HostingOptionByIdResult'
    hostingsOptions: 'HostingOptionsResult'
    languageOptionById: 'LanguageOptionByIdResult'
    languagesOptions: 'LanguageOptionsResult'
    mediaById: 'MediaByIdResult'
    medias: 'MediasResult'
    reviewById: 'ReviewByIdResult'
    reviews: 'ReviewsResult'
    searchDonations: 'SearchDonationsResult'
    serviceOptionById: 'ServiceOptionByIdResult'
    servicesOptions: 'ServiceOptionsResult'
    specieOptionById: 'SpecieOptionByIdResult'
    speciesOptions: 'SpecieOptionsResult'
    staffById: 'StaffByIdResult'
    userById: 'UserByIdResult'
  }
  ReviewsList: { // field return type name
    reviews: 'Review'
  }
  ServiceOption: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    nameEn: 'String'
    nameFr: 'String'
    updatedAt: 'DateTime'
  }
  ServiceOptionsList: { // field return type name
    serviceOptions: 'ServiceOption'
  }
  SharedMedia: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    mediaType: 'MediaType'
    operator: 'Operator'
    operatorId: 'ID'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'ID'
  }
  SpecieOption: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    nameEn: 'String'
    nameFr: 'String'
    updatedAt: 'DateTime'
  }
  SpecieOptionsList: { // field return type name
    specieOptions: 'SpecieOption'
  }
  Staff: { // field return type name
    access: 'String'
    createdAt: 'DateTime'
    email: 'String'
    id: 'String'
    phoneNumber: 'String'
    updatedAt: 'DateTime'
  }
  StaffsList: { // field return type name
    staffs: 'Staff'
  }
  StorageInfos: { // field return type name
    signedRequest: 'String'
    url: 'String'
  }
  StripePayment: { // field return type name
    booking: 'Booking'
    bookingId: 'ID'
    createdAt: 'DateTime'
    errorCode: 'String'
    id: 'String'
    status: 'PaymentStatus'
    updatedAt: 'DateTime'
  }
  Subscription: { // field return type name
    errorsEmailCronSub: 'CronSubscriptionsResult'
    pendingPaymentCronSub: 'CronSubscriptionsResult'
    setupIntentCronSub: 'CronSubscriptionsResult'
  }
  UnableToProcessError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  User: { // field return type name
    accountId: 'ID'
    createdAt: 'DateTime'
    firstName: 'String'
    id: 'String'
    lastName: 'String'
    updatedAt: 'DateTime'
  }
  UserAuthenticationError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  UserBookingMessage: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    medias: 'Media'
    readAt: 'DateTime'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'ID'
  }
  UserClaim: { // field return type name
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    reason: 'String'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'ID'
  }
  UserForbiddenError: { // field return type name
    code: 'ErrorCode'
    message: 'ErrorMessage'
  }
  UserMedia: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    mediaType: 'MediaType'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'ID'
  }
  UserReview: { // field return type name
    body: 'String'
    booking: 'Booking'
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    score: 'Float'
    title: 'String'
    updatedAt: 'DateTime'
    user: 'User'
    userId: 'ID'
  }
  UsersList: { // field return type name
    users: 'User'
  }
  Actor: { // field return type name
    accountId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    updatedAt: 'DateTime'
  }
  BookingMessage: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    medias: 'Media'
    readAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  Claim: { // field return type name
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    reason: 'String'
    updatedAt: 'DateTime'
  }
  Media: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    mediaType: 'MediaType'
    storeUrl: 'URL'
    updatedAt: 'DateTime'
  }
  Node: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    updatedAt: 'DateTime'
  }
  Operator: { // field return type name
    acceptedSpecieOptionsIds: 'String'
    accountId: 'ID'
    calendarUpdate: 'DateTime'
    createdAt: 'DateTime'
    description: 'String'
    hostingOptionId: 'String'
    id: 'String'
    languageOptionIds: 'String'
    mainMediaId: 'String'
    ownAnimalsSpecieOptionsIds: 'String'
    partnerId: 'String'
    partnerPercentage: 'Int'
    stripeAccountId: 'String'
    updatedAt: 'DateTime'
  }
  Payment: { // field return type name
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    status: 'PaymentStatus'
    updatedAt: 'DateTime'
  }
  Review: { // field return type name
    body: 'String'
    booking: 'Booking'
    bookingId: 'ID'
    createdAt: 'DateTime'
    id: 'String'
    score: 'Float'
    title: 'String'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createAccount: { // args
      input: NexusGenInputs['CreateAccountInput']; // CreateAccountInput!
    }
    createBookingClaim: { // args
      input: NexusGenInputs['CreateBookingClaimInput']; // CreateBookingClaimInput!
    }
    createBookingMessage: { // args
      input: NexusGenInputs['CreateBookingMessageInput']; // CreateBookingMessageInput!
    }
    createGenderOption: { // args
      input: NexusGenInputs['CreateGenderOptionInput']; // CreateGenderOptionInput!
    }
    createHostingOption: { // args
      input: NexusGenInputs['CreateHostingOptionInput']; // CreateHostingOptionInput!
    }
    createIndividualOperator: { // args
      input: NexusGenInputs['CreateIndividualOperatorInput']; // CreateIndividualOperatorInput!
    }
    createLanguageOption: { // args
      input: NexusGenInputs['CreateLanguageOptionInput']; // CreateLanguageOptionInput!
    }
    createMedia: { // args
      input: NexusGenInputs['CreateMediaInput']; // CreateMediaInput!
    }
    createReview: { // args
      input: NexusGenInputs['CreateReviewInput']; // CreateReviewInput!
    }
    createServiceOption: { // args
      input: NexusGenInputs['CreateServiceOptionInput']; // CreateServiceOptionInput!
    }
    createSpecieOption: { // args
      input: NexusGenInputs['CreateSpecieOptionInput']; // CreateSpecieOptionInput!
    }
    createStaffAccount: { // args
      input: NexusGenInputs['CreateStaffAccountInput']; // CreateStaffAccountInput!
    }
    deleteAccount: { // args
      confirmPassword: string; // String!
    }
    deleteBookingMessage: { // args
      id: string; // ID!
    }
    deleteClaim: { // args
      id: string; // ID!
    }
    deleteGenderOption: { // args
      id: string; // ID!
    }
    deleteHostingOption: { // args
      id: string; // ID!
    }
    deleteLanguageOption: { // args
      id: string; // ID!
    }
    deleteMedia: { // args
      mediaId: string; // ID!
    }
    deleteReview: { // args
      id: string; // ID!
    }
    deleteServiceOption: { // args
      id: string; // ID!
    }
    deleteSpecieOption: { // args
      id: string; // ID!
    }
    lostPassword: { // args
      email: string; // String!
    }
    modifyEmail: { // args
      email: string; // String!
    }
    modifyPassword: { // args
      newPassword: string; // String!
      password: string; // String!
    }
    resetPassword: { // args
      input: NexusGenInputs['ResetPasswordInput']; // ResetPasswordInput!
    }
    sendVerificationEmail: { // args
      email: string; // String!
    }
    setAsRead: { // args
      input: NexusGenInputs['SetBookingMessagesAsReadInput']; // SetBookingMessagesAsReadInput!
    }
    signIn: { // args
      input: NexusGenInputs['EmailAndPasswordInput']; // EmailAndPasswordInput!
    }
    startCron: { // args
      cronName: string; // String!
    }
    stopCron: { // args
      cronName: string; // String!
    }
    updateBookingMessage: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateBookingMessageInput']; // UpdateBookingMessageInput!
      saveAs: string; // String!
    }
    updateGenderOption: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateGenderOptionInput']; // UpdateGenderOptionInput!
    }
    updateHostingOption: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateHostingOptionInput']; // UpdateHostingOptionInput!
    }
    updateIndividualOperator: { // args
      input: NexusGenInputs['CreateIndividualOperatorInput']; // CreateIndividualOperatorInput!
    }
    updateLanguageOption: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateLanguageOptionInput']; // UpdateLanguageOptionInput!
    }
    updateReview: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateReviewInput']; // UpdateReviewInput!
      saveAs: string; // String!
    }
    updateServiceOption: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateServiceOptionInput']; // UpdateServiceOptionInput!
    }
    updateSpecieOption: { // args
      id: string; // ID!
      input: NexusGenInputs['UpdateSpecieOptionInput']; // UpdateSpecieOptionInput!
    }
    verifyUser: { // args
      input: NexusGenInputs['VerifyUserInput']; // VerifyUserInput!
    }
  }
  Query: {
    accountById: { // args
      id: string; // ID!
    }
    bookingMessageById: { // args
      id: string; // ID!
    }
    claimById: { // args
      id: string; // ID!
    }
    donationById: { // args
      id: string; // ID!
    }
    genderOptionById: { // args
      id: string; // ID!
    }
    getCronStatus: { // args
      cronName: string; // String!
    }
    hostingOptionById: { // args
      id: string; // ID!
    }
    languageOptionById: { // args
      id: string; // ID!
    }
    mediaById: { // args
      id: string; // ID!
    }
    reviewById: { // args
      id: string; // ID!
    }
    searchDonations: { // args
      input: NexusGenInputs['SearchDonationsInput']; // SearchDonationsInput!
    }
    serviceOptionById: { // args
      id: string; // ID!
    }
    specieOptionById: { // args
      id: string; // ID!
    }
    staffById: { // args
      id: string; // ID!
    }
    userById: { // args
      id: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  AccountByIdResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  AccountResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  AllAccountsResult: "AccountsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  AllStaffsResult: "StaffsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  AllUsersResult: "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError" | "UsersList"
  BookingMessageByIdResult: "InvalidArgumentsError" | "NotFoundError" | "OperatorBookingMessage" | "UserAuthenticationError" | "UserBookingMessage" | "UserForbiddenError"
  BookingMessagesResult: "BookingMessagesList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  BookingPayment: "StripePayment"
  ClaimByIdResult: "NotFoundError" | "OperatorClaim" | "UserAuthenticationError" | "UserClaim" | "UserForbiddenError"
  ClaimsResult: "ClaimsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateAccountResult: "Account" | "InvalidArgumentsError" | "UnableToProcessError"
  CreateBookingClaimResult: "InvalidArgumentsError" | "OperatorClaim" | "UnableToProcessError" | "UserAuthenticationError" | "UserClaim"
  CreateBookingMessageResult: "InvalidArgumentsError" | "OperatorBookingMessage" | "UnableToProcessError" | "UserAuthenticationError" | "UserBookingMessage"
  CreateGenderOptionResult: "GenderOption" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateHostingOptionResult: "HostingOption" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateIndividualOperatorResult: "IndividualOperator" | "InvalidArgumentsError" | "UnableToProcessError"
  CreateLanguageOptionResult: "InvalidArgumentsError" | "LanguageOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateMediaResult: "InvalidArgumentsError" | "StorageInfos" | "UnableToProcessError" | "UserAuthenticationError"
  CreateReviewResult: "InvalidArgumentsError" | "OperatorReview" | "UnableToProcessError" | "UserAuthenticationError" | "UserReview"
  CreateServiceOptionResult: "InvalidArgumentsError" | "ServiceOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateSpecieOptionResult: "InvalidArgumentsError" | "SpecieOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CreateStaffAccountResult: "Account" | "InvalidArgumentsError" | "UnableToProcessError"
  CronSubscriptionsResult: "BooleanResult" | "UserAuthenticationError" | "UserForbiddenError"
  CurrentAccountResult: "Account" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  CurrentOperatorDonationsResult: "DonationsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  CurrentOperatorMediaResult: "NotFoundError" | "OperatorMedia" | "SharedMedia" | "UserAuthenticationError" | "UserForbiddenError"
  CurrentUserMediaResult: "NotFoundError" | "SharedMedia" | "UserAuthenticationError" | "UserForbiddenError" | "UserMedia"
  DeleteAccountResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError"
  DeleteBookingMessageResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError"
  DeleteClaimResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError"
  DeleteGenderOptionResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  DeleteHostingOptionResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  DeleteLanguageOptionResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  DeleteMediaResult: "BooleanResult" | "InvalidArgumentsError" | "IsActiveOperatorMainMediaError" | "IsActiveOperatorWithNoReplacementMediaError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError"
  DeleteReviewResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError"
  DeleteServiceOptionResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  DeleteSpecieOptionResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  DonationByIdResult: "Donation" | "InvalidArgumentsError" | "NotFoundError"
  DonationsResult: "DonationsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  GenderOptionByIdResult: "GenderOption" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  GenderOptionsResult: "GenderOptionsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  GetCronStatusResult: "CronStatus" | "UserAuthenticationError" | "UserForbiddenError"
  HostingOptionByIdResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  HostingOptionsResult: "HostingOptionsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  IndividualOperatorResult: "IndividualOperator" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  LanguageOptionByIdResult: "InvalidArgumentsError" | "LanguageOption" | "NotFoundError" | "UserAuthenticationError" | "UserForbiddenError"
  LanguageOptionsResult: "LanguageOptionsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  LostPasswordResult: "BooleanResult" | "NotFoundError"
  MediaByIdResult: "InvalidArgumentsError" | "NotFoundError" | "OperatorMedia" | "SharedMedia" | "UserAuthenticationError" | "UserForbiddenError" | "UserMedia"
  MediasResult: "MediasList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  ModifyEmailResult: "Account" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError"
  ModifyPasswordResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UserAuthenticationError"
  ResetPasswordResult: "BooleanResult" | "InvalidArgumentsError" | "UnableToProcessError"
  ReviewByIdResult: "InvalidArgumentsError" | "NotFoundError" | "OperatorReview" | "UserAuthenticationError" | "UserForbiddenError" | "UserReview"
  ReviewsResult: "ReviewsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  SearchDonationsResult: "DonationsList" | "InvalidArgumentsError" | "UnableToProcessError"
  SendVerificationEmailResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  ServiceOptionByIdResult: "InvalidArgumentsError" | "NotFoundError" | "ServiceOption" | "UserAuthenticationError" | "UserForbiddenError"
  ServiceOptionsResult: "ServiceOptionsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  SetBookingMessagesAsReadResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError" | "UserAuthenticationError"
  SignInResult: "Account" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  SignOutResult: "BooleanResult" | "UserAuthenticationError"
  SpecieOptionByIdResult: "InvalidArgumentsError" | "NotFoundError" | "SpecieOption" | "UserAuthenticationError" | "UserForbiddenError"
  SpecieOptionsResult: "SpecieOptionsList" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  StaffByIdResult: "InvalidArgumentsError" | "NotFoundError" | "Staff" | "UserAuthenticationError" | "UserForbiddenError"
  StartCronResult: "BooleanResult" | "UserAuthenticationError" | "UserForbiddenError"
  StopCronResult: "BooleanResult" | "UserAuthenticationError" | "UserForbiddenError"
  UpdateBookingMessageResult: "InvalidArgumentsError" | "NotFoundError" | "OperatorBookingMessage" | "UnableToProcessError" | "UserAuthenticationError" | "UserBookingMessage"
  UpdateGenderOptionResult: "GenderOption" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  UpdateHostingOptionResult: "HostingOption" | "InvalidArgumentsError" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  UpdateIndividualOperatorResult: "IndividualOperator" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  UpdateLanguageOptionResult: "InvalidArgumentsError" | "LanguageOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  UpdateReviewResult: "InvalidArgumentsError" | "NotFoundError" | "OperatorReview" | "UnableToProcessError" | "UserAuthenticationError" | "UserReview"
  UpdateServiceOptionResult: "InvalidArgumentsError" | "ServiceOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  UpdateSpecieOptionResult: "InvalidArgumentsError" | "SpecieOption" | "UnableToProcessError" | "UserAuthenticationError" | "UserForbiddenError"
  UserByIdResult: "InvalidArgumentsError" | "NotFoundError" | "User" | "UserAuthenticationError" | "UserForbiddenError"
  VerifyUserResult: "BooleanResult" | "InvalidArgumentsError" | "NotFoundError" | "UnableToProcessError"
  Actor: "IndividualOperator" | "User"
  BookingMessage: "OperatorBookingMessage" | "UserBookingMessage"
  Claim: "OperatorClaim" | "UserClaim"
  Media: "DonationReceiptMedia" | "LanguageOptionMedia" | "MessageMedia" | "OperatorMedia" | "SharedMedia" | "UserMedia"
  Node: "Account" | "Booking" | "Donation" | "DonationReceipt" | "DonationReceiptMedia" | "GenderOption" | "HostingOption" | "IndividualOperator" | "LanguageOption" | "LanguageOptionMedia" | "MessageMedia" | "OperatorBookingMessage" | "OperatorClaim" | "OperatorMedia" | "OperatorReview" | "ServiceOption" | "SharedMedia" | "SpecieOption" | "Staff" | "StripePayment" | "User" | "UserBookingMessage" | "UserClaim" | "UserMedia" | "UserReview"
  Operator: "IndividualOperator"
  Payment: "StripePayment"
  Review: "OperatorReview" | "UserReview"
}

export interface NexusGenTypeInterfaces {
  Account: "Node"
  Booking: "Node"
  Donation: "Node"
  DonationReceipt: "Node"
  DonationReceiptMedia: "Media" | "Node"
  GenderOption: "Node"
  HostingOption: "Node"
  IndividualOperator: "Actor" | "Node" | "Operator"
  LanguageOption: "Node"
  LanguageOptionMedia: "Media" | "Node"
  MessageMedia: "Media" | "Node"
  OperatorBookingMessage: "BookingMessage" | "Node"
  OperatorClaim: "Claim" | "Node"
  OperatorMedia: "Media" | "Node"
  OperatorReview: "Node" | "Review"
  ServiceOption: "Node"
  SharedMedia: "Media" | "Node"
  SpecieOption: "Node"
  Staff: "Node"
  StripePayment: "Node" | "Payment"
  User: "Actor" | "Node"
  UserBookingMessage: "BookingMessage" | "Node"
  UserClaim: "Claim" | "Node"
  UserMedia: "Media" | "Node"
  UserReview: "Node" | "Review"
  Actor: "Node"
  BookingMessage: "Node"
  Claim: "Node"
  Media: "Node"
  Operator: "Actor" | "Node"
  Payment: "Node"
  Review: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = "Account" | "AccountsList" | "Booking" | "BookingMessagesList" | "BooleanResult" | "ClaimsList" | "CronStatus" | "Donation" | "DonationReceipt" | "DonationReceiptMedia" | "DonationsList" | "GenderOption" | "GenderOptionsList" | "HostingOption" | "HostingOptionsList" | "IndividualOperator" | "InvalidArgumentsError" | "IsActiveOperatorMainMediaError" | "IsActiveOperatorWithNoReplacementMediaError" | "LanguageOption" | "LanguageOptionMedia" | "LanguageOptionsList" | "MediasList" | "MessageMedia" | "NotFoundError" | "OperatorBookingMessage" | "OperatorClaim" | "OperatorMedia" | "OperatorReview" | "ReviewsList" | "ServiceOption" | "ServiceOptionsList" | "SharedMedia" | "SpecieOption" | "SpecieOptionsList" | "Staff" | "StaffsList" | "StorageInfos" | "StripePayment" | "UnableToProcessError" | "User" | "UserAuthenticationError" | "UserBookingMessage" | "UserClaim" | "UserForbiddenError" | "UserMedia" | "UserReview" | "UsersList";

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: true
    __typename: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: ApiContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Validation for an individual field. Returning "undefined"
     * or "Promise<undefined>" means the field can be accessed.
     * Returning InvalidArgumentsError or "Promise<InvalidArgumentsError>" will prevent the resolver from executing.
     */
    validation?: FieldValidationResolver<TypeName, FieldName>
    /**
     * Authorization for an individual field. Returning "undefined"
     * or "Promise<undefined>" means the field can be accessed.
     * Returning "UserAuthenticationError" will prevent the resolver from executing.
     */
    authorization?: FieldAuthorizationResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}