export const PAYMENT_STATUS = {
	PENDING_AUTHORIZATION: 'PENDING_AUTHORIZATION' as 'PENDING_AUTHORIZATION',
	SETUP_INTENT_PENDING_CONFIRMATION:
		'SETUP_INTENT_PENDING_CONFIRMATION' as 'SETUP_INTENT_PENDING_CONFIRMATION',
	SETUP_INTENT_CONFIRMED_REQUIRED_PAYMENT_INTENT_CREATION:
		'SETUP_INTENT_CONFIRMED_REQUIRED_PAYMENT_INTENT_CREATION' as 'SETUP_INTENT_CONFIRMED_REQUIRED_PAYMENT_INTENT_CREATION',
	FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS:
		'FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS' as 'FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS',
	FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED:
		'FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED' as 'FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED',
	FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR:
		'FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR' as 'FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR',
	FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED_MAIL_SENT:
		'FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED_MAIL_SENT' as 'FAILED_PAYMENT_INTENT_CREATION_AUTH_REQUIRED_MAIL_SENT',
	FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS_MAIL_SENT:
		'FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS_MAIL_SENT' as 'FAILED_PAYMENT_INTENT_CREATION_INSUFFICIENT_FUNDS_MAIL_SENT',
	FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR_MAIL_SENT:
		'FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR_MAIL_SENT' as 'FAILED_PAYMENT_INTENT_CREATION_UNKOWN_ERROR_MAIL_SENT',
	ERROR_SENDING_AUTH_REQUIRED_MAIL:
		'ERROR_SENDING_AUTH_REQUIRED_MAIL' as 'ERROR_SENDING_AUTH_REQUIRED_MAIL',
	ERROR_SENDING_INSUFFICIENT_FUNDS_MAIL:
		'ERROR_SENDING_INSUFFICIENT_FUNDS_MAIL' as 'ERROR_SENDING_INSUFFICIENT_FUNDS_MAIL',
	ERROR_SENDING_UNKOWN_ERROR_MAIL:
		'ERROR_SENDING_UNKOWN_ERROR_MAIL' as 'ERROR_SENDING_UNKOWN_ERROR_MAIL',
	AUTHORIZED_REQUIRE_CAPTURE: 'AUTHORIZED_REQUIRE_CAPTURE' as 'AUTHORIZED_REQUIRE_CAPTURE',
	AUTHORIZED_BUT_CANCELLED: 'AUTHORIZED_BUT_CANCELLED' as 'AUTHORIZED_BUT_CANCELLED',
	CAPTURED_AND_PAID: 'CAPTURED_AND_PAID' as 'CAPTURED_AND_PAID',
	FAILED_CAPTURE: 'FAILED_CAPTURE' as 'FAILED_CAPTURE'
}

export const STRIPE_TARGET_APIS = {
	SETUP_INTENT: 'SETUP_INTENT' as 'SETUP_INTENT',
	PAYMENT_INTENT: 'PAYMENT_INTENT' as 'PAYMENT_INTENT'
}
